version: "3"

services:
  app:
    build: .
    command:
      [
        "sh",
        "-c",
        "pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000",
      ]
    volumes:
      - ./app/:/app/app
    ports:
      - 8000:8000
      - 5678:5678

volumes:
  app:
